postgresql_version: 13
postgresql_configuration_directory: /var/lib/pgsql/{{ postgresql_version }}/data
max_connections: 100
shared_buffers: 128MB
random_page_cost: 4.0
hoh_db: hoh

# pgo placeholders, the following is set to empty to make sure the ansible runs fine on VM instead of using postgres creds
db_login_host:  ""
db_login_user:  ""
db_login_password: ""
db_ssl_mode: "require"
# end of pgo

hoh_process_user: hoh-process-user
transport_bridge_user: transport-bridge-user
spec_schema: spec
status_schema: status
local_spec_schema: local_spec
local_status_schema: local_status
history_schema: history
# according to Kubernetes DNS label standard https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
cluster_name_length_limit: 63
managed_clusters_table: managed_clusters
managed_clusters_labels_table: managed_clusters_labels
managed_cluster_sets_tracking_table: managed_cluster_sets_tracking
policies_table: compliance
aggregated_policies_table: aggregated_compliance
leaf_hub_heartbeats_table: leaf_hub_heartbeats
subscriptions_table: subscriptions
enforcement_type: enforcement_type
compliance_type: compliance_type
error_type: error_type
set_timestamp_trigger: set_timestamp
move_to_history_trigger: move_to_history
