---
- name: create spec tables
  tags: tables
  vars:
    database: "{{ hoh_db }}"
  include_tasks: create_spec_table.yaml
  loop:
    - policies
    - placementrules
    - placementbindings
    - configs
    - subscriptions
    - channels
    - applications
    - clusterdeployments
    - secrets
    - machinepools
    - klusterletaddonconfigs
  loop_control:
    loop_var: name
  import_tasks: create_spec_managedclusters_table.yaml
