---
- name: list all tables in {{ hoh_db }}.{{ schema }} as a sanity check
  postgresql_query:
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    query: "SELECT schemaname,tablename FROM pg_catalog.pg_tables where schemaname='{{ schema }}';"
  become: yes
  become_user: postgres
  register: list_all_tables_result

- name: all tables as a sanity check output
  ansible.builtin.debug:
    msg: "{{ list_all_tables_result.query_all_results }}"
