---
- name: set password encryption
  lineinfile:
    path: "{{ postgresql_configuration_directory }}/postgresql.conf"
    regexp: '^password_encryption'
    line: password_encryption = scram-sha-256
    state: present

- name: reload the server
  systemd:
    name: "postgresql-{{ postgresql_version }}"
    enabled: true
    state: reloaded