---
  # using shell inbstead of dnf task due to a certificate problem
- name: install postgresql RPM
  shell: dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  args:
      warn: false

- name: install postgresql
  dnf:
    name:
      - "postgresql{{ postgresql_version }}-server"
      - "postgresql{{ postgresql_version }}-contrib"
      - "postgresql{{ postgresql_version }}-devel"

- name: initialize the server
  shell: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ postgresql_version }}-setup initdb"
  args:
    creates: "{{ postgresql_configuration_directory }}/pg_hba.conf"

- name: start the server
  systemd:
    name: "postgresql-{{ postgresql_version }}"
    enabled: true
    state: started

- name: create a softlink for pg_config
  file:
    src: /usr/pgsql-{{ postgresql_version }}/bin/pg_config
    dest: /usr/sbin/pg_config
    state: link

- name: install dependencies for ansible postgres
  pip:
    name:
      - psycopg2
    executable: pip3
    extra_args: "--user"
  become: false
