---
- name: install
  import_tasks: install_postgres_server.yaml


- name: perform tuning
  import_tasks: perform_tuning.yaml

- name: create users
  import_tasks: create_databases.yaml

# for pgo the user is created when operator initialized ../../../pgo/high-availability/ha-postgres.yaml:10,13
- name: create users
  import_tasks: create_users.yaml

- name: dump the current databases as a sanity check
  shell: psql -c '\l'
  become: yes
  become_user: postgres
  register: databases_psql_databases_result

- name: database sanity debug
  ansible.builtin.debug:
    msg: "{{ databases_psql_databases_result.stdout_lines }}"

