---
- name: set usage permissions on schemas
  postgresql_privs:
    db: "{{ hoh_db }}"
    privs: USAGE
    type: schema
    objs: "{{ spec_schema }},{{ status_schema }},{{ history_schema }},{{ local_spec_schema }},{{ local_status_schema }}"
    role: "{{ hoh_process_user }},{{ transport_bridge_user }}"
  become: yes
  become_user: postgres

- name: set permissions on spec schema for hoh_process_user
  postgresql_privs:
    db: "{{ hoh_db }}"
    privs: SELECT,INSERT,UPDATE,DELETE
    type: table
    objs: ALL_IN_SCHEMA
    schema: "{{ spec_schema }}"
    role: "{{ hoh_process_user }}"
  become: yes
  become_user: postgres

- name: set permissions on spec schema for transport_bridge_user
  postgresql_privs:
    db: "{{ hoh_db }}"
    privs: SELECT
    type: table
    objs: ALL_IN_SCHEMA
    schema: "{{ spec_schema }}"
    role: "{{ transport_bridge_user }}"
  become: yes
  become_user: postgres

- name: set permissions on status schema for hoh_process_user
  postgresql_privs:
    db: "{{ hoh_db }}"
    privs: SELECT
    type: table
    objs: ALL_IN_SCHEMA
    schema: "{{ status_schema }}"
    role: "{{ hoh_process_user }}"
  become: yes
  become_user: postgres

- name: set permissions on history schema for hoh_process_user
  postgresql_privs:
    db: "{{ hoh_db }}"
    privs: SELECT,INSERT
    type: table
    objs: ALL_IN_SCHEMA
    schema: "{{ history_schema }}"
    role: "{{ hoh_process_user }}"
  become: yes
  become_user: postgres

- name: set permissions on status schema for transport_bridge_user
  postgresql_privs:
    db: "{{ hoh_db }}"
    privs: SELECT,INSERT,UPDATE,DELETE
    type: table
    objs: ALL_IN_SCHEMA
    schema: "{{ status_schema }}"
    role: "{{ transport_bridge_user }}"
  become: yes
  become_user: postgres

- name: set permissions on local status schema for transport_bridge_user
  postgresql_privs:
    db: "{{ hoh_db }}"
    privs: SELECT,INSERT,UPDATE,DELETE
    type: table
    objs: ALL_IN_SCHEMA
    schema: "{{ local_status_schema }}"
    role: "{{ transport_bridge_user }}"
  become: yes
  become_user: postgres

- name: set permissions on local spec schema for transport_bridge_user
  postgresql_privs:
    db: "{{ hoh_db }}"
    privs: SELECT,INSERT,UPDATE,DELETE
    type: table
    objs: ALL_IN_SCHEMA
    schema: "{{ local_spec_schema }}"
    role: "{{ transport_bridge_user }}"
  become: yes
  become_user: postgres
